version: 1
datastore:
  user: testuser
  password: testpass
  hostname: mysqldb
  port: 3306
  db: travel_info
events:
  hostname: kafka
  port: 9092
  topic: events
engine:
  pool_recycle: 500
  pool_pre_ping: True
  pool_size: 5