version: 1
datastore:
  filepath: ./data/processing.json
scheduler:
  interval: 5
eventstores:
  attraction_info:
    url: http://storage:8090/storage/get/attractions
  expense_info:
    url: http://storage:8090/storage/get/expenses